### ISSUE TITLE
jackson-module-kotlin causes picnic to throw NoSuchMethodError

### ISSUE THREAD

**Issue by AlexandreCarlton** [kscripting/kscript#286]
Thanks for creating and maintaining this project, it has been great to work with so far!

Including [FasterXML/jackson-module-kotlin](https://github.com/FasterXML/jackson-module-kotlin) alongside usage of [JakeWharton/picnic](https://github.com/JakeWharton/picnic) causes the script to throw a non-obvious exception:

```kotlin
#!/usr/bin/env kscript

@file:DependsOn("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.3")
@file:DependsOn("com.jakewharton.picnic:picnic:0.5.0")

import com.jakewharton.picnic.table

println(table { row("Hello, world!") })
```

```
❯ ./picnic.kts
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at Main_Picnic$Companion.main(Main_Picnic.kt:6)
        at Main_Picnic.main(Main_Picnic.kt)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:64)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:149)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:159)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
        at com.jakewharton.picnic.TextRendering$renderText$1.<init>(textRender.kt)
        at com.jakewharton.picnic.TextRendering$renderText$1.<clinit>(textRender.kt)
        at com.jakewharton.picnic.TextRendering.render$default(textRender.kt:15)
        at com.jakewharton.picnic.Table.toString(model.kt:12)
        at java.lang.String.valueOf(String.java:2994)
        at java.io.PrintStream.println(PrintStream.java:821)
        at Picnic.<init>(picnic.kts:8)
        ... 13 more
```

Removing the `@file:DependsOn("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.3")` allows the script to pass.

An equivalent Gradle project that includes both of these dependencies does not result in throwing an exception, so it appears to be unique to `kscript`.

Unfortunately, downgrading Kotlin to `1.4.0` or `1.3.72` does not help unlike #279 so I figured this should be a separate ticket.

Versions:
 - Kotlin `1.4.10`
 - `kscript` `2.9.3`

Thanks!

**Comment by aartiPl** [comment]
In the recent kscript version above example works as expected. Interestingly picnic 0.6.0 jar file seems to be broken: it contains strange kotlin_metadata files instead of class files. 
Anyway, I am closing this ticket, as everything works as expected now.
