### ISSUE TITLE
[4.1.1] Increase logging detail for dependency resolution errors

### ISSUE THREAD

**Issue by Tzrlk** [kscripting/kscript#386]
When attempting to resolve dependencies from within a corporate environment, the errors I receive don't provide me enough information to assist in resolving them.
```
[kscript] Resolving com.squareup:kotlinpoet:1.12.0...
[kscript] [DEV] Resolved in: 632
[kscript] Resolving io.ktor:ktor-client-core:2.1.3...
[kscript] [DEV] Resolved in: 62
[kscript] Resolving io.ktor:ktor-client-cio:2.1.3...
[kscript] [DEV] Resolved in: 67
[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.)of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] File 'com.squareup:kotlinpoet:1.12.0' not found
[kscript] [ERROR] org.jetbrains.kotlin.org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for com.squareup:kotlinpoet:jar:1.12.0
[kscript] [ERROR] org.jetbrains.kotlin.org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for com.squareup:kotlinpoet:jar:1.12.0
[kscript] [ERROR]
[kscript] [ERROR] java.lang.IllegalStateException: Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.)of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] File 'com.squareup:kotlinpoet:1.12.0' not found
[kscript] [ERROR] org.jetbrains.kotlin.org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for com.squareup:kotlinpoet:jar:1.12.0
[kscript] [ERROR] org.jetbrains.kotlin.org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for com.squareup:kotlinpoet:jar:1.12.0
[kscript] [ERROR]       at kscript.app.resolver.DependencyResolver$resolve$resolvedDependencies$2.invoke(DependencyResolver.kt:59)
[kscript] [ERROR]       at kscript.app.resolver.DependencyResolver$resolve$resolvedDependencies$2.invoke(DependencyResolver.kt:50)
[kscript] [ERROR]       at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
[kscript] [ERROR]       at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
[kscript] [ERROR]       at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
[kscript] [ERROR]       at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
[kscript] [ERROR]       at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
[kscript] [ERROR]       at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
[kscript] [ERROR]       at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:827)
[kscript] [ERROR]       at kscript.app.resolver.DependencyResolver.resolve(DependencyResolver.kt:65)
[kscript] [ERROR]       at kscript.app.KscriptHandler$handle$resolvedDependencies$1.invoke(KscriptHandler.kt:74)
[kscript] [ERROR]       at kscript.app.KscriptHandler$handle$resolvedDependencies$1.invoke(KscriptHandler.kt:73)
[kscript] [ERROR]       at kscript.app.cache.Cache.getOrCreateDependencies(Cache.kt:101)
[kscript] [ERROR]       at kscript.app.KscriptHandler.handle(KscriptHandler.kt:73)
[kscript] [ERROR]       at kscript.app.KscriptKt.main(Kscript.kt:46)
[kscript] [ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[kscript] [ERROR]       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[kscript] [ERROR]       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[kscript] [ERROR]       at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[kscript] [ERROR]       at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:64)
[kscript] [ERROR]       at org.jetbrains.kotlin.runner.Main.run(Main.kt:176)
[kscript] [ERROR]       at org.jetbrains.kotlin.runner.Main.main(Main.kt:186)
```
In the above log, there is no mention of what caused the dependency resolution error, beyond that there was one. Knowing what kind of http response was returned would go a long way.

**Comment by aartiPl** [comment]
The Kotlin component does dependency resolution:
kotlin.script.experimental.dependencies.maven.MavenDependenciesResolver

I have rechecked, but everything available from that component is already used for debug printing in kscript.
So any extended logging should be requested from the Kotlin scripting component.

**Comment by Tzrlk** [comment]
Well damn. I guess I'll put something up there when I get back to this.
